### ISSUE TITLE
Enable Blended Screen Space Reflections and Global Light settings don't persist

### ISSUE THREAD

**Issue by JaidynBelbin** [sammilucia/cyberpunk-ultra-plus#21]
As the title says. Currently testing out the beta10 (just downloaded straight from here), and every reload, those two settings which I wish to have always on are turned off.

Also the "Enable Separate RTXDI Denoising" seems to turn on/off at will. If I'm using PTNext, what should it be set to?

Thanks.

**Comment by ZER0exe1** [comment]
Globallight is not working correctly and Serparate denoising gets turned off in the main menu and gets reenabled whenever you are in game to stop it from causing issues
