### ISSUE TITLE
CTD near Jig-Jig street on versions newer than 5.1.1

### ISSUE THREAD

**Issue by marcinsobala** [sammilucia/cyberpunk-ultra-plus#27]
Hi! 
My game always CTDs whenever I'm near Jig-Jig street and I have ultra plus mod on. It happens for PTNext and PT 2.1. I tested multiple versions from nexus file archive and the newest one that works without CTDs is 5.1.1. Using versions 5.2.4 and up always result in the same problem.

I'm attaching 2 error reports:
[ReportQueue.zip](https://github.com/user-attachments/files/16736596/ReportQueue.zip)

My specs:
- game ver 2.12
- RTX 4090
- CPU AMD Ryzen 7 7800X3D 8-Core Processor
- Windows 11

**Comment by saitz** [comment]
any news on that?

**Comment by robber804** [comment]
i think i may have found a work around, i will create a pull request, not 100% sure this fixes the issue but it has worked for me and i have done a lot of testing on it.

**Comment by blackecos** [comment]
This sounds like the issue I’m having at the moment. It's not at Jig-Jig Street, but it’s in the same corner.
Only crash with PTNext or PT20 no crash with RT+PT or without the mod.
Still crashing if I have only Ultra+ and requierment active.

![CP-Crash](https://github.com/user-attachments/assets/36807fa5-569f-4ab4-b3a5-bc0796271094)

**Comment by marcinsobala** [comment]
I no longer have this issue in version 5.3.2. Whatever you did, thank you, @sammilucia 🙂
